# Generated by Django 5.2.8 on 2025-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(blank=True, to='posts.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='post',
            name='vk_video_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВК видео'),
        ),
    ]
