# Generated by Django 5.2.8 on 2025-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_tag_post_is_pinned_post_post_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ'),
        ),
    ]
