# Generated by Django 6.0.2 on 2026-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postcomment_options_alter_postreaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/comments/', verbose_name='Фото'),
        ),
    ]
