# Generated by Django 5.2.8 on 2025-11-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('time_text', models.CharField(blank=True, max_length=100, verbose_name='Время проведения')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Обложка')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткое описание')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communities.community', verbose_name='ID группы')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
    ]
