# Generated by Django 5.2.8 on 2025-11-21 13:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Длинное описание (HTML)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.CharField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
