# Generated by Django 5.2.8 on 2025-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
