# Generated by Django 5.2.8 on 2025-11-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='communities/covers/', verbose_name='Обложка')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткое описание')),
                ('links', models.JSONField(blank=True, help_text='Список ссылок в формате [{title, url}]', null=True, verbose_name='Прикреплённые ссылки')),
                ('videos', models.JSONField(blank=True, help_text='Список видео (url)', null=True, verbose_name='Видео для описания')),
                ('photos', models.JSONField(blank=True, help_text='Список url или id изображений', null=True, verbose_name='Фотографии для описания')),
                ('long_description', models.TextField(blank=True, verbose_name='Длинное описание (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Владелец?')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления/создания')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Член сообщества',
                'verbose_name_plural': 'Члены сообществ',
            },
        ),
    ]
