# Generated by Django 5.2.8 on 2025-11-17 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_slug_alter_community_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='links',
        ),
        migrations.RemoveField(
            model_name='community',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='community',
            name='videos',
        ),
        migrations.CreateModel(
            name='CommunityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ссылки')),
                ('url', models.URLField(verbose_name='URL')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Ссылка сообщества',
                'verbose_name_plural': 'Ссылки сообщества',
            },
        ),
        migrations.CreateModel(
            name='CommunityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='communities/photos/', verbose_name='Фотография')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Фото сообщества',
                'verbose_name_plural': 'Фотографии сообщества',
            },
        ),
    ]
