# Generated by Django 5.2.8 on 2025-11-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_remove_community_links_remove_community_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitylink',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_links', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='communityphoto',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_photos', to='communities.community', verbose_name='Сообщество'),
        ),
    ]
