# Generated by Django 5.2.8 on 2025-11-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_communitylink_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='community_tags',
            field=models.ManyToManyField(blank=True, to='communities.communitytag'),
        ),
    ]
