# Generated by Django 5.2.8 on 2025-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communitytag_community_community_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_tags',
            field=models.ManyToManyField(blank=True, related_name='communities', to='communities.communitytag'),
        ),
    ]
