# Generated by Django 6.0.2 on 2026-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_community_community_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='subscribe_price',
            field=models.IntegerField(default=0, help_text='Если 0 то бесплатная', verbose_name='Стоимость подписки'),
        ),
    ]
