# Generated by Django 6.0.2 on 2026-03-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_community_subscribe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityphoto',
            name='vk_video_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВК видео'),
        ),
        migrations.AlterField(
            model_name='communityphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communities/photos/', verbose_name='Фотография'),
        ),
        migrations.CreateModel(
            name='CommunityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Опсание')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_rules', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Правило сообщества',
                'verbose_name_plural': 'Правила сообщества',
            },
        ),
    ]
