# Generated by Django 6.0.2 on 2026-03-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_communityphoto_vk_video_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВК видео')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_videos', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'ВК видео сообщества',
                'verbose_name_plural': 'ВК видео сообщества',
            },
        ),
    ]
