# Generated by Django 6.0.2 on 2026-03-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_communityvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityphoto',
            name='vk_video_link',
        ),
    ]
