# Generated by Django 5.2.8 on 2025-11-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='infoproducts/covers/', verbose_name='Обложка')),
                ('big_cover', models.ImageField(blank=True, null=True, upload_to='infoproducts/big_covers/', verbose_name='Обложка большая')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткое описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('long_description', models.TextField(blank=True, verbose_name='Большое описание (HTML)')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoproducts', to='communities.community', verbose_name='ID группы')),
            ],
            options={
                'verbose_name': 'Инфопродукт',
                'verbose_name_plural': 'Инфопродукты',
            },
        ),
        migrations.CreateModel(
            name='InfoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='infoproducts/photos/', verbose_name='Фото преимущества')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='infoproducts.infoproduct')),
            ],
        ),
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='infoproducts/files/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='infoproducts.infoproduct')),
            ],
        ),
    ]
