# Generated by Django 5.2.8 on 2025-11-17 06:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='long_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Большое описание (HTML)'),
        ),
    ]
