# Generated by Django 5.2.8 on 2025-11-19 13:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoproducts', '0002_infoproduct_slug_alter_infoproduct_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='product_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Большое описание (HTML)'),
        ),
        migrations.DeleteModel(
            name='InfoPhoto',
        ),
    ]
