# Generated by Django 5.2.8 on 2025-11-20 14:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoproducts', '0003_infoproduct_product_info_delete_infophoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='big_cover',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='long_description',
        ),
        migrations.AddField(
            model_name='infoproduct',
            name='product_info_structure',
            field=models.JSONField(blank=True, null=True, verbose_name='Сруктура html'),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='product_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Большое описание (HTML)'),
        ),
    ]
