# Generated by Django 6.0.2 on 2026-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoproducts', '0004_remove_infoproduct_big_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='main_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка на курс'),
        ),
    ]
